module.exports = {
  Dashboard: require("./Dashboard"),
  Logo: require("./Logo"),
  User: require("./User"),
  Sheet: require("./Sheet"),
  SheetData: require("./SheetData"),
  Chart: require("./Charts"),
  Tab: require("./Tab"),
  SheetTab: require("./SheetTabs"),
  Plan: require("./Plans"),
  UserPlan: require("./UserPlans"),
  SharedDashboard: require("./sharedDashboards"),
  // userDb: require("./userDb"),
  Archive: require("./archive"),
};
